class MarkdownReport:

    @staticmethod
    def generate(
        security_review,
        code_review,
        performance_review,
        remediation,
        risk_report,
        summary,
        metrics=None
    ):

        metrics = metrics or {}

        return f"""
# CodeGuard AI Enterprise Review Report

---

## Executive Summary

{summary}

---

## Security Analysis

{security_review}

---

## Code Quality Analysis

{code_review}

---

## Performance Analysis

{performance_review}

---

## Risk Assessment

{risk_report}

---

## Remediation Plan

{remediation}

---

## Dashboard

| Metric | Value |
|----------|----------|
| High Severity | {metrics.get('high',0)} |
| Medium Severity | {metrics.get('medium',0)} |
| Low Severity | {metrics.get('low',0)} |
| Health Score | {metrics.get('health_score',0)} |

---

Generated by CodeGuard AI
"""