import json
import streamlit as st
from app.utils.ui import load_css

load_css()

# =====================================================
# PAGE
# =====================================================

st.title("📄 Reports")

st.caption(
    "View and download the latest CodeGuard analysis report."
)

st.divider()

# =====================================================
# CHECK REPORT
# =====================================================

if "result" not in st.session_state:

    st.warning("No report available.")

    st.info(
        "Run an analysis from the Dashboard first."
    )

    st.stop()

# =====================================================
# LOAD REPORT
# =====================================================

result = st.session_state["result"]

project = result["project"]

code_analysis = result["code_analysis"]

security = result["security"]

remediation = result["remediation"]

summary = result["summary"]

# =====================================================
# PROJECT DETAILS
# =====================================================

st.header("📊 Project Information")

c1, c2, c3, c4 = st.columns(4)

c1.metric(
    "Language",
    project["language"]
)

c2.metric(
    "Filename",
    project["filename"]
)

c3.metric(
    "Lines",
    project["lines_of_code"]
)

c4.metric(
    "Health Score",
    f'{summary["health_score"]}/100'
)

st.progress(summary["health_score"] / 100)

st.divider()

# =====================================================
# SUMMARY
# =====================================================

st.header("📄 Pull Request Summary")

st.markdown(summary["summary"])

st.divider()

# =====================================================
# CODE ANALYSIS
# =====================================================

st.header("📋 Code Analysis")

st.metric(
    "Findings",
    code_analysis["total_findings"]
)

if code_analysis["findings"]:

    for finding in code_analysis["findings"]:

        with st.expander(
            finding["title"]
        ):

            st.write(
                f"Severity : {finding['severity']}"
            )

            st.write(
                f"Line : {finding['line_number']}"
            )

            st.write(
                finding["description"]
            )

            st.info(
                finding["suggestion"]
            )

else:

    st.success(
        "No code quality issues detected."
    )

st.divider()

# =====================================================
# SECURITY
# =====================================================

st.header("🔒 Security Findings")

critical = security["critical"]

high = security["high"]

medium = security["medium"]

low = security["low"]

a, b, c, d = st.columns(4)

a.metric("Critical", critical)

b.metric("High", high)

c.metric("Medium", medium)

d.metric("Low", low)

if security["findings"]:

    for finding in security["findings"]:

        with st.expander(
            finding["title"]
        ):

            st.write(
                f"Severity : {finding['severity']}"
            )

            st.write(
                f"Line : {finding['line_number']}"
            )

            st.write(
                finding["description"]
            )

            st.warning(
                finding["suggestion"]
            )

else:

    st.success(
        "No security vulnerabilities detected."
    )

st.divider()

# =====================================================
# REMEDIATION
# =====================================================

st.header("🛠 AI Remediation")

st.markdown(

    remediation["result"]

)

st.divider()

# =====================================================
# EXPORT
# =====================================================

st.header("⬇ Download Reports")

json_report = json.dumps(

    result,

    indent=4

)

markdown_report = f"""
# CodeGuard v3 Report

## Project

Language : {project['language']}

Filename : {project['filename']}

Lines : {project['lines_of_code']}

Health Score : {summary['health_score']}

---

# Pull Request Summary

{summary['summary']}

---

Generated by CodeGuard v3
"""

left, right = st.columns(2)

with left:

    st.download_button(

        "⬇ Download JSON",

        json_report,

        file_name="codeguard_report.json",

        mime="application/json",

        use_container_width=True

    )

with right:

    st.download_button(

        "⬇ Download Markdown",

        markdown_report,

        file_name="codeguard_report.md",

        mime="text/markdown",

        use_container_width=True

    )

st.divider()

# =====================================================
# FOOTER
# =====================================================

st.caption(

    "🛡️ CodeGuard v3 | AI Code Review & Security Analysis"

)