from __future__ import annotations

from app.agents.analysis.models import Finding


class FindingDeduplicator:
    """
    Removes duplicate findings generated by multiple analyzers.

    Duplicate criteria:
        • tool
        • file
        • line
        • rule
        • message
    """

    @staticmethod
    def deduplicate(
        findings: list[Finding],
    ) -> list[Finding]:
        """
        Remove duplicate findings while preserving order.

        Parameters
        ----------
        findings : list[Finding]

        Returns
        -------
        list[Finding]
        """

        unique: dict[
            tuple[str, str, int, str, str],
            Finding,
        ] = {}

        for finding in findings:

            key = (
                finding.tool,
                finding.file,
                finding.line,
                finding.rule or "",
                finding.message,
            )

            if key not in unique:
                unique[key] = finding

        return list(unique.values())

    @staticmethod
    def count_duplicates(
        findings: list[Finding],
    ) -> int:
        """
        Count duplicate findings.

        Returns
        -------
        int
        """

        seen = set()

        duplicates = 0

        for finding in findings:

            key = (
                finding.tool,
                finding.file,
                finding.line,
                finding.rule or "",
                finding.message,
            )

            if key in seen:

                duplicates += 1

            else:

                seen.add(key)

        return duplicates